"""模型层规则测试：铁律在 Pydantic 校验中的体现。"""
import pytest
from pydantic import ValidationError

from qresearch.core.models import CheckItem, Decision, Hypothesis
from qresearch.core.status import DecisionRecommendation, DecisionType


def test_hypothesis_requires_falsification_tests():
    with pytest.raises(ValidationError):
        Hypothesis(project_id="p", statement="某相存在于中间耦合区", falsification_tests=[])
    ok = Hypothesis(project_id="p", statement="某相存在于中间耦合区",
                    falsification_tests=["扫描耦合区间并计算序参量"])
    assert ok.status == "proposed"


def test_passed_check_item_requires_evidence():
    with pytest.raises(ValidationError):
        CheckItem(claim="能量已收敛", status="passed")
    ok = CheckItem(claim="能量已收敛", status="passed", evidence="evidence_001")
    assert ok.evidence == "evidence_001"
    # failed/untested 允许无证据，但应给出原因
    CheckItem(claim="假设未检验", status="untested", reason="缺大尺寸数据")


def test_declare_result_requires_human():
    with pytest.raises(ValidationError):
        Decision(project_id="p", type=DecisionType.DECLARE_RESULT,
                 recommendation=DecisionRecommendation.ACCEPT, requires_human=False)
    d = Decision(project_id="p", type=DecisionType.DECLARE_RESULT,
                 recommendation=DecisionRecommendation.ACCEPT)
    assert d.requires_human is True


def test_ids_and_timestamps_autogenerated():
    h = Hypothesis(project_id="p", statement="s", falsification_tests=["对照解析解"])
    assert h.hypothesis_id.startswith("hyp_")
    assert h.created_at.tzinfo is not None


def test_enum_json_roundtrip():
    h = Hypothesis(project_id="p", statement="s", falsification_tests=["x"])
    h2 = Hypothesis.model_validate_json(h.model_dump_json())
    assert h2 == h
